Repository CrisisCleanup/crisiscleanup-3-web, pull requests merged in 2020-05, with the labels that each got.

#684 Localization update
  src/components/FileUpload.vue
  src/components/TermsandConditionsModal.vue
  src/components/WorksiteFilters.vue
  src/components/reports/ExampleReports.vue
  src/layouts/Authenticated.vue
  src/pages/Dashboard.vue
  src/pages/Reports.vue
  src/pages/home/About.vue
  src/pages/phone_legacy/ConnectFirstIntegration.vue
  src/router.js
  src/services/phone.service.js
  src/store/modules/phone.js
  src/utils/data_filters/Filter.js
Labels: localization

#687 CaseForm: require at least one worktype
  src/pages/CaseForm.vue
Labels: cases, medium, ui, ux

#704 Localizations: Icon Alt text, ID, No Items Found
  src/components/Autocomplete.vue
  src/components/BaseInput.vue
  src/components/FormSelect.vue
  src/components/LocationTable.vue
  src/components/Table.vue
  src/components/Tag.vue
  src/components/WorksiteSearchInput.vue
  src/components/__tests__/Tag.test.js
  src/components/__tests__/__snapshots__/FormSelect.test.js.snap
  src/components/__tests__/__snapshots__/Storyshots.test.js.snap
  src/components/admin/GhostUsersTable.vue
  src/components/admin/OrganizationsTable.vue
  src/components/admin/UsersTable.vue
  src/components/cards/case/CaseTile.vue
  src/pages/__tests__/__snapshots__/Dashboard.test.js.snap
  src/pages/admin/AdminOrganization.vue
Labels: localization, ui, ux

#713 Localizations
  src/components/FileUpload.vue
  src/layouts/Authenticated.vue
  src/pages/CaseForm.vue
  src/pages/OtherOrganizations.vue
  src/pages/admin/AdminOrganization.vue
  src/pages/home/About.vue
  src/router.js
  src/services/phone.service.js
  src/store/modules/phone.js
Labels: localization
